### ISSUE TITLE
Overwrite Default Snippet Files

### ISSUE THREAD

**Issue by dev-head** [Nordstrom/chef-gen-flavors#19]
Is there support to override the files that the default snippets use?

### Example: 

Using my own custom snippet I add:

```rb
      def snippet_setup_files(recipe)
        #@templates_if_missing << '.kitchen.yml'
      end
```
In my flavor I do: 

```rb
      include ChefGen::Snippet::MySnippet
      include ChefGen::Snippet::TestKitchen
```

This results in the content of the .kitchen.yml file being managed by the TestKitchen snippet and a warning from chef, shown below. I would expect, perhaps naively, that the TestKitchen would not add it's .kitchen.yml since it exists in the hash already when I added it to my custom snippet. 

```sh
WARN: Cloning resource attributes for template[/path/to/cookbook/.kitchen.yml] from prior resource (CHEF-3694)
WARN: Previous template[/path/to/cookbook/.kitchen.yml]: /path/to/gems/chef-gen-flavors-0.8.3/lib/chef_gen/flavor_base.rb:224:in `_add_resource'
WARN: Current  template[/path/to/cookbook/.kitchen.yml]: /path/to/gems/chef-gen-flavors-0.8.3/lib/chef_gen/flavor_base.rb:224:in `_add_resource'
```

Perhaps I am missing this completely but worth asking in case there is a supported method to handle this. 

My current work arounds: 

- don't use the TestKitchen snippet and implement my own. 
- fork the repo and modify the default files

@jf647 Any ideas to get this working?

Thanks.

**Comment by jf647** [comment]
Sorry for the delay.  I've been thinking about this and had a brainstorm this morning.

The issue isn't the declaration (because you also want a a .kitchen.yml in the root of your generated cookbook).  What you want is to ensure that your source file ends up in the temporary source dir rather than the one that ships with chef-gen-flavors.

In the current release, each snippet does the copying directly, which makes this order dependent.  If you could ensure that your snippet always ran after the default one, then you could just copy yours and get that guarantee.  But without playing lexical ordering games, you'd never be certain that your snippet hadn't been called before the default.

We could let each snippet define a priority, and then call them in that order, to give you the guarantee.  I toyed with this when I was developing the release that added content files, but gave it up when I realized that you can't define a constant or method called 'priority' on each snippet, because they're all included into one class and only the first one takes effect.

In retrospect, if I get the constant directly from the snippet module, I should be able to impose some order.  Perhaps even a class and priority, so that people can hook in before or after the core snippets if they need to.

Thoughts on this approach?  It's a breaking change, but that's still OK under semver before we hit 1.0.0.  I'm not sure how many people are using flavor base.  I know some people are using flavors for distribution, but at least one is not using flavor base, so this wouldn't affect them.
